defmodule SddOrchestratorWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :sdd_orchestrator

  # Browser authorization lives in one signed, persistent, HttpOnly, Secure
  # session cookie. Server-side session records still enforce their own absolute
  # expiry and revocation before protected data is returned.
  #
  # `secure` defaults to true and stays true everywhere the app is served over
  # HTTPS. Local development serves plain HTTP, and a browser that enforces the
  # Secure attribute strictly on `http://localhost` — Safari does — never sends
  # the cookie back, which silently breaks the OAuth callback: the nonce stored
  # before the redirect is simply absent when GitHub returns.
  @session_options [
    store: :cookie,
    key: "_sdd_orchestrator_key",
    signing_salt: "Rb9qupER",
    same_site: "Lax",
    http_only: true,
    secure: Application.compile_env(:sdd_orchestrator, :session_cookie_secure, true),
    max_age: 30 * 24 * 60 * 60
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, session: @session_options]],
    longpoll: [connect_info: [:peer_data, session: @session_options]]

  # Workers dial in over TLS, so a local or user-managed worker needs no inbound
  # port. Long polling is not offered: command delivery is a server push and a
  # worker holds its connection open for as long as it can execute.
  socket "/worker", SddOrchestratorWeb.WorkerSocket,
    websocket: [connect_info: [:peer_data]],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :sdd_orchestrator,
    gzip: not code_reloading?,
    only: SddOrchestratorWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :sdd_orchestrator
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug SddOrchestratorWeb.Router
end
