defmodule SddOrchestrator.ProjectAssistant.ProjectContextStore.Hosted do
  @moduledoc false

  import Ecto.Query

  alias SddOrchestrator.Accounts.PersonalWorkspace
  alias SddOrchestrator.ProjectAssistant.ProjectContextAssembler
  alias SddOrchestrator.ProjectAssistant.ProjectContextProjection
  alias SddOrchestrator.Repo

  @spec refresh(PersonalWorkspace.t(), String.t(), map()) ::
          {:ok, ProjectContextProjection.t()} | {:error, :unauthorized | term()}
  def refresh(%PersonalWorkspace{} = authority, project_id, actor) do
    with {:ok, assembled} <- ProjectContextAssembler.assemble(authority, project_id, actor) do
      upsert(project_id, assembled)
    end
  end

  @spec get(PersonalWorkspace.t(), String.t(), map()) ::
          {:ok, ProjectContextProjection.t() | nil} | {:error, :unauthorized}
  def get(%PersonalWorkspace{} = authority, project_id, actor) do
    with {:ok, _project} <- ProjectContextAssembler.Hosted.authorize(authority, project_id, actor) do
      {:ok, Repo.get_by(ProjectContextProjection, project_id: project_id)}
    end
  end

  @spec delete(PersonalWorkspace.t(), String.t(), map()) :: :ok | {:error, :unauthorized}
  def delete(%PersonalWorkspace{} = authority, project_id, actor) do
    with {:ok, _project} <- ProjectContextAssembler.Hosted.authorize(authority, project_id, actor) do
      ProjectContextProjection
      |> where([p], p.project_id == ^project_id)
      |> Repo.delete_all()

      :ok
    end
  end

  # One project, one row: re-assembling replaces the single current
  # projection instead of accumulating stale history, the same idempotent
  # replace-in-place `RepositoryPilotSelection` already uses for its one
  # current pilot.
  defp upsert(project_id, %{content: content, context_version: version}) do
    now = DateTime.utc_now() |> DateTime.truncate(:second)

    %ProjectContextProjection{}
    |> ProjectContextProjection.upsert_changeset(%{
      project_id: project_id,
      context_version: version,
      content: content,
      refreshed_at: now
    })
    |> Repo.insert(
      conflict_target: :project_id,
      on_conflict: {:replace, [:context_version, :content, :refreshed_at, :updated_at]},
      # `:id` is deliberately excluded from the replace list, so a conflict
      # keeps the project's existing row identity; `returning: true` is what
      # makes the returned struct reflect that real (pre-existing) id and
      # `inserted_at` instead of the freshly autogenerated values the local
      # changeset attempted to insert with.
      returning: true
    )
  end
end
