import Config

# Configure your database
config :sdd_orchestrator, SddOrchestrator.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: 5433,
  database: System.get_env("DATABASE_NAME", "sdd_orchestrator_dev"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sdd_orchestrator, SddOrchestratorWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "l7822rZvIoLTNRACPJ8wDZNUoDB4kTf7aKqhaiEphCA0C8us8ZvD5A0BQ3qBGHPO",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:sdd_orchestrator, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:sdd_orchestrator, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :sdd_orchestrator, dev_routes: true

# Expose the non-product design-system preview at /_ui in development.
config :sdd_orchestrator, :ui_preview, true

# Field-encryption vault. This non-production key is intentionally checked in for
# local development only; production supplies CLOAK_KEY at runtime.
config :sdd_orchestrator, SddOrchestrator.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1", key: Base.decode64!("3YLEhIU/FRrY0Rkv8c0vhwsD/yqMSRtmfv+IUAURsmo=")}
  ]

# Load local secrets from a git-ignored `.env` (KEY=value lines) so `mix phx.server`
# picks up the GitHub App credentials without exporting them on every command. Only
# runs in dev; values set here feed the env reads below.
env_file = Path.expand("../.env", __DIR__)

if File.exists?(env_file) do
  for line <- File.stream!(env_file),
      trimmed = String.trim(line),
      trimmed != "",
      not String.starts_with?(trimmed, "#"),
      [key, value] <- [String.split(trimmed, "=", parts: 2)],
      value != nil do
    System.put_env(String.trim(key), String.trim(value))
  end
end

# GitHub App for local development. Configure real credentials via env when
# exercising a live sign-in; the deterministic fake provider is used in tests.
# The app private key is optional; the pending installation-request lookup
# degrades gracefully to the grant screen when it is absent.
config :sdd_orchestrator, :github,
  app_origin: System.get_env("APP_ORIGIN", "http://localhost:4000"),
  client_id: System.get_env("GITHUB_CLIENT_ID", "dev-client-id"),
  client_secret: System.get_env("GITHUB_CLIENT_SECRET", "dev-client-secret"),
  app_id: System.get_env("GITHUB_APP_ID"),
  app_private_key: System.get_env("GITHUB_APP_PRIVATE_KEY")

config :sdd_orchestrator, :passwordless,
  app_origin: System.get_env("APP_ORIGIN", "http://localhost:4000")

# Durable local DeviceStore standing in for the native worker in development.
config :sdd_orchestrator, SddOrchestrator.Devices.DeviceStore.Local,
  start: true,
  path: "priv/device_store/dev.dets"

# Enable the local worker stand-in so the graphical local-onboarding flow (pairing
# completion and folder selection) is exercisable without the signed native worker.
config :sdd_orchestrator, :device_worker_stub, true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
