import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :sdd_orchestrator, SddOrchestratorWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :sdd_orchestrator, SddOrchestratorWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# A started run reaches the worker only when something turns its durable
# command into the envelope the worker executes. Production runs the real
# channel transport against the real stored records; a command it cannot build
# an envelope for stays queued rather than being delivered or lost.
config :sdd_orchestrator,
  command_transport: SddOrchestrator.Delivery.CommandTransport.Channel,
  command_envelope_source: SddOrchestrator.Delivery.CommandTransport.StartEnvelopeSource

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
