import Foundation

/// Builds the `bin/worker rpc` expression that stores a **projectless**
/// worker configuration and starts `SddOrchestrator.Worker.Supervisor`
/// under the already-running embedded release, for a worker paired from
/// this app's menu bar (specs/39 Task 2, AC-01).
///
/// Structurally the same call as `PostPairingRPCExpressionBuilder.build`
/// — read the temporary configuration JSON file
/// (`MacPairingConfigurationBuilder`'s output, written to disk by
/// `MacPairingRetention`), `Jason.decode!/1` it, construct
/// `%SddOrchestrator.Worker.Configuration{}` directly rather than through
/// `Configuration.from_pairing/2` (which expects the `mix worker.pair` CLI
/// path's intermediate shape), then `Configuration.store/2` and
/// `DynamicSupervisor.start_child(SddOrchestrator.Application.worker_host_name(),
/// SddOrchestrator.Worker.Supervisor)`. `rpc`, never `eval`, because `rpc`
/// targets the release's already-booted node (the one
/// `WorkerProcessController` started), while `eval` would boot a separate,
/// short-lived VM that would never affect the real running worker.
///
/// The one difference is the one this task exists for: the struct literal
/// names only the six fields specs/39 Task 1 left required. It sets
/// neither `project_id:` nor `workspace_root:` at all, so both take the
/// struct's own `nil` default — the shape `Configuration` now writes as an
/// absent key. Setting them to `nil` explicitly would produce the same
/// struct, but it would also read as "this app decided the worker has no
/// project", when in truth this pairing was never told about one.
///
/// A separate builder rather than a widened
/// `PostPairingRPCExpressionBuilder`: that one is specs/36's verified
/// deep-link path, which this slice's boundary explicitly excludes from
/// change. `Outcome` and `parse(_:)` are reused from it rather than
/// duplicated, because the release prints the same three answers either
/// way, and two copies of that parser could drift apart.
///
/// Only the temporary file's own path — generated by this app itself
/// (`sdd-orchestrator-mac-pairing-<UUID>`, never an operator- or
/// pairing-response-supplied string) — is interpolated into the
/// expression. All six configuration values, the credential included,
/// travel only inside the JSON file's contents and are never logged or
/// printed.
enum MacPairingRPCExpressionBuilder {
    /// The release prints exactly the same `ok:`/`error:` answers here as
    /// it does on specs/36's path, so this reuses that outcome type rather
    /// than declaring a second one that would have to be kept in step.
    typealias Outcome = PostPairingRPCExpressionBuilder.Outcome

    static func build(configFilePath: String) -> String {
        let escapedPath = elixirStringLiteral(configFilePath)

        return """
        try do
          {:ok, contents} = File.read("\(escapedPath)")
          data = Jason.decode!(contents)

          config = %SddOrchestrator.Worker.Configuration{
            control_plane_address: Map.fetch!(data, "control_plane_address"),
            device_workspace_id: Map.fetch!(data, "device_workspace_id"),
            worker_credential: Map.fetch!(data, "worker_credential"),
            agent_adapter: Map.fetch!(data, "agent_adapter"),
            agent_executable: Map.fetch!(data, "agent_executable"),
            worker_id: Map.fetch!(data, "worker_id")
          }

          :ok = SddOrchestrator.Worker.Configuration.store(config, nil)

          case DynamicSupervisor.start_child(
                 SddOrchestrator.Application.worker_host_name(),
                 SddOrchestrator.Worker.Supervisor
               ) do
            {:ok, _pid} -> IO.puts("ok:started")
            {:error, {:already_started, _pid}} -> IO.puts("ok:already_started")
            {:error, reason} -> IO.puts("error:" <> inspect(reason))
          end
        rescue
          e -> IO.puts("error:" <> Exception.message(e))
        end
        """
    }

    /// Escapes backslashes and double quotes for embedding inside an Elixir
    /// double-quoted string literal. Defense in depth: this app generates
    /// `configFilePath` itself from a UUID (alphanumeric and hyphens only)
    /// under `NSTemporaryDirectory()`, so no unsafe character is actually
    /// expected here — this only guards against the OS temp-directory
    /// prefix itself ever containing one. Kept private and duplicated from
    /// `PostPairingRPCExpressionBuilder` rather than shared, because
    /// hoisting it would edit that file, and specs/36's verified expression
    /// stays byte-identical in this slice.
    private static func elixirStringLiteral(_ raw: String) -> String {
        raw
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }

    static func parse(_ result: CommandResult) -> Outcome {
        PostPairingRPCExpressionBuilder.parse(result)
    }
}
