import Foundation

/// Builds the `bin/worker rpc` expression that stores the worker
/// configuration and starts `SddOrchestrator.Worker.Supervisor` under the
/// already-running embedded release, and parses its output.
///
/// The expression reads the temporary configuration JSON file
/// (`PostPairingConfigurationBuilder`'s output, written to disk by
/// `PostPairingSetupCoordinatorImpl`), decodes it with `Jason.decode!/1`,
/// and constructs `%SddOrchestrator.Worker.Configuration{}` directly —
/// never `Configuration.from_pairing/2`, which expects a different
/// intermediate shape built for the `mix worker.pair` CLI path (see
/// `Mix.Tasks.Worker.Pair`). It then calls
/// `SddOrchestrator.Worker.Configuration.store/2` and
/// `DynamicSupervisor.start_child(SddOrchestrator.Application.worker_host_name(),
/// SddOrchestrator.Worker.Supervisor)` — `rpc`, never `eval`, because `rpc`
/// targets the release's already-booted node (the one
/// `WorkerProcessController` started), while `eval` would boot a separate,
/// short-lived VM that would never affect the real running worker.
///
/// Only the temporary file's own path — generated by this app itself
/// (`sdd-orchestrator-worker-setup-<UUID>`, never an operator- or
/// pairing-response-supplied string) — is interpolated into the
/// expression. Every one of the eight actual configuration values,
/// including the credential and the operator-picked workspace path (either
/// of which may contain characters unsafe to splice directly into Elixir
/// source), travels only inside the JSON file's contents and is never
/// logged or printed.
enum PostPairingRPCExpressionBuilder {
    enum Outcome: Equatable {
        /// `DynamicSupervisor.start_child` returned `{:ok, _pid}`.
        case started
        /// `DynamicSupervisor.start_child` returned
        /// `{:error, {:already_started, _pid}}` — setup already completed
        /// on an earlier attempt. Treated as success, per this task's
        /// idempotency requirement.
        case alreadyStarted
        /// The expression ran but reported a failure reason (a `rescue`d
        /// exception, or `Configuration.store/2`/`start_child` returning an
        /// error tuple).
        case failure(String)
        /// The process itself failed: non-zero exit, timeout, or output
        /// that matches neither the `ok:`/`error:` shape below.
        case commandFailed
    }

    static func build(configFilePath: String) -> String {
        let escapedPath = elixirStringLiteral(configFilePath)

        return """
        try do
          {:ok, contents} = File.read("\(escapedPath)")
          data = Jason.decode!(contents)

          config = %SddOrchestrator.Worker.Configuration{
            control_plane_address: Map.fetch!(data, "control_plane_address"),
            device_workspace_id: Map.fetch!(data, "device_workspace_id"),
            worker_credential: Map.fetch!(data, "worker_credential"),
            agent_adapter: Map.fetch!(data, "agent_adapter"),
            agent_executable: Map.fetch!(data, "agent_executable"),
            workspace_root: Map.fetch!(data, "workspace_root"),
            project_id: Map.fetch!(data, "project_id"),
            worker_id: Map.fetch!(data, "worker_id")
          }

          :ok = SddOrchestrator.Worker.Configuration.store(config, nil)

          case DynamicSupervisor.start_child(
                 SddOrchestrator.Application.worker_host_name(),
                 SddOrchestrator.Worker.Supervisor
               ) do
            {:ok, _pid} -> IO.puts("ok:started")
            {:error, {:already_started, _pid}} -> IO.puts("ok:already_started")
            {:error, reason} -> IO.puts("error:" <> inspect(reason))
          end
        rescue
          e -> IO.puts("error:" <> Exception.message(e))
        end
        """
    }

    /// Escapes backslashes and double quotes for embedding inside an Elixir
    /// double-quoted string literal. Defense in depth: this app generates
    /// `configFilePath` itself from a UUID (alphanumeric and hyphens only)
    /// under `NSTemporaryDirectory()`, so no unsafe character is actually
    /// expected here — this only guards against the OS temp-directory
    /// prefix itself ever containing one.
    private static func elixirStringLiteral(_ raw: String) -> String {
        raw
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }

    static func parse(_ result: CommandResult) -> Outcome {
        guard !result.timedOut, result.exitCode == 0 else { return .commandFailed }

        let trimmed = result.standardOutput.trimmingCharacters(in: .whitespacesAndNewlines)

        switch trimmed {
        case "ok:started": return .started
        case "ok:already_started": return .alreadyStarted
        default:
            if trimmed.hasPrefix("error:") {
                return .failure(String(trimmed.dropFirst("error:".count)))
            }
            return .commandFailed
        }
    }
}
